Repository hngi/fury-backend-node, pull requests merged in 2020-06, with the labels that each got.

#14 PR - [feature]: Setup basic tests
  .eslintignore
  .eslintrc.js
  __tests__/api/index.test.js
  __tests__/api/utils.test.js
  __tests__/app.test.js
  __tests__/config/setup.js
  __tests__/db/db-create.test.js
  babel.config.js
  config/default.js
  config/test.json
  jest.config.js
  package-lock.json
  package.json
  sample.env
  sample.env.test
  src/api/db/sql/db-create.sql
Labels: chore, feature

#45 Swagger API Docs Task 2
  src/api/index.js
  src/api/swagger-spec.js
  src/api/v1/jsdocs/employees.yaml
Labels: feature

#49 Swagger API Docs Task 4
  src/api/v1/jsdocs/employees.yaml
Labels: feature

#51 Swagger API Task 5
  src/api/v1/jsdocs/employees.yaml
Labels: feature

#56 Swagger API Docs Task 7
  src/api/v1/jsdocs/departments.yaml
  src/api/v1/jsdocs/employees.yaml
Labels: feature

#58 Swagger API Docs Task 8
  src/api/v1/jsdocs/departments.yaml
  src/api/v1/jsdocs/employees.yaml
Labels: feature

#60 Swagger API Docs Task 9
  src/api/v1/jsdocs/departments.yaml
Labels: feature

#66 Documentation Task 1
  README.md
Labels: feature

#69 PR - [refactor]: Move swaggerspec and change baseUrl
  src/api/index.js
  src/api/utils/swaggerSpec.js
  src/api/v1/routes/index.js
Labels: chore

#70 Merge master into develop
  .gitignore
  README.md
  __tests__/api/middleware.test.js
  employee_controller.js
  employee_route.js
  package-lock.json
  package.json
  sample.env
  sample.env.test
  src/api/db/create-db.js
  src/api/db/sql/db-create.sql
  src/api/index.js
  src/api/routes/employee/createEmployee.js
  src/api/utils/errorhandler.js
  src/api/utils/swaggerSpec.js
  src/api/utils/validationRules.js
  src/api/v1/controllers/index.js
  src/api/v1/jsdocs/departments.yaml
  src/api/v1/jsdocs/employees.yaml
  src/api/v1/middleware/index.js
  src/api/v1/middleware/validationMiddleware.js
  src/api/v1/routes/index.js
  src/index.js
Labels: chore

#73 PR - [feature]: Create configure endpoint
  src/api/db/index.js
  src/api/db/sql/db-create.sql
  src/api/utils/responseHandler.js
  src/api/utils/validationRules.js
  src/api/v1/routes/index.js
Labels: enhancement

#83 [bugfix]: Remove DB user ownership
  config/default.js
  config/production.json
  src/api/db/create-db.js
  src/api/db/sql/db-create.sql
  src/api/v1/routes/index.js
Labels: bug

#82 Ft department apis
  src/api/utils/validationRules.js
  src/api/v1/controllers/departmentController.js
  src/api/v1/controllers/employeeController.js
  src/api/v1/routes/index.js
Labels: feature

#91 [FEATURE REQUEST]: Implementation Employees Endpoint Task 2 #71
  src/api/utils/validationRules.js
  src/api/v1/controllers/departmentController.js
  src/api/v1/controllers/employeeController.js
  src/api/v1/routes/index.js
Labels: feature

#92 FIX: change departmentId from string to integer
  src/api/v1/jsdocs/employees.yaml
Labels: expert

#93 FIX: update index test to expect swagger ui snapshot
  __tests__/api/__snapshots__/index.test.js.snap
  __tests__/api/index.test.js
Labels: expert
